# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build info
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
  jobs:
    post_checkout:
      - git fetch --unshallow origin || true
      - git fetch origin "+refs/heads/*:refs/remotes/origin/*" --prune
      - git branch -r
    install:
      - pip install --editable .[docs]
    build:
      html:
        - BUILDDIR=$READTHEDOCS_OUTPUT SPHINXOPTS=-W make -C doc html 
