from typing import Any

from .base import MPILoggedTask

class AccumulateList(MPILoggedTask):
    group_size: int
    _items: list[Any]
    def __init__(self) -> None: ...
    def next(self, input_: Any) -> Any | None: ...
    def finish(self) -> Any | None: ...

class Delete(MPILoggedTask):
    def process(self, x: Any) -> None: ...

class MakeCopy(MPILoggedTask):
    def process(self, data: Any) -> Any: ...

class PassOn(MPILoggedTask):
    def next(self, input_: Any) -> Any: ...

class WaitUntil(MPILoggedTask):
    def setup(self, input_: Any): ...
    def next(self, input_: Any) -> Any: ...
